[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["cd api && pip install -r requirements.txt"]

[start]
cmd = "cd api && python -m uvicorn simple_app:app --host 0.0.0.0 --port $PORT"
