[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["cd api && python -m pip install --user -r requirements.txt"]

[start]
cmd = "cd api && python -m uvicorn app:app --host 0.0.0.0 --port $PORT"
